/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uc10.regex;


import java.util.logging.Level;
import java.util.logging.Logger;

public class App {

    public static void main(String[] args) {
        Logger logger = Logger.getLogger("App");

        if (args.length == 0) {
            logger.log(Level.WARNING, " Please provide command line arguments:\n" +
                    " 1) string to validate against regex\n" +
                    " 2) max number of characters the string allowed to have.");
            return;
        }

        String inputString = args[0];
        int passedMaxLength = Integer.parseInt(args[1]);

        boolean validationResult = RegexValidationUtil.validateAll(inputString, passedMaxLength);

        logger.log(Level.INFO, "Validation result for input string - {0} - is {1}", new Object[]{inputString, (validationResult ? "valid" : "invalid")});
    }
}
