/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uc10.regex;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void appValidatesInput() {
        //too much effort to set up test to check log messages
        App.main(new String[]{"yK$z8tU0V6h4", "12"});
    }
}
